### ISSUE TITLE
Deploying Using Github Pages

### ISSUE THREAD

**Issue by ch4ne5teban** [ch4ne5teban/my-portfolio#8]
I deployed my website last week using Github Pages. Therefore, opening an issue rather than a pull request. Here's the link to the online version of my portfolio site: https://ch4ne5teban.github.io/my-portfolio/

**Comment by ShadyShawkat** [comment]
## Hi @ch4ne5teban, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Things to consider 💡 
 - [ ] Kindly edit your `readme` so that your live demo link is below it's respective section for more visual clarity.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ch4ne5teban** [comment]
@ShadyShawkat Thank you for the suggestion. I'll implement it in a bit.
